version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    # links:
    #   - server
