version: "2"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - api
  api:
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    image: farmenvyapi:latest
    environment:
      - PORT=5000
    volumes:
      - ./:/usr/src/api
      - /usr/src/api/tmp
      - /usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
    links:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
    - /var/lib/postgresql/data


